---
- hosts: compute
  name: Change DHCP/DNS Domain in nova and neutron
  become: yes
  vars_files:
    - vars.yml
  tasks:
    - name: Change dhcp_domain in nova.conf
      lineinfile:
        dest: /etc/nova/nova.conf
        regexp: '^dhcp_domain='
        line: 'dhcp_domain={{ nova_domain }}'
    - name: restart openstack-nova-compute
      service:
        name: openstack-nova-compute
        state: restarted
    - name: Change dhcp_domain in neutron dhcp_agent.ini
      lineinfile:
        dest: /etc/neutron/dhcp_agent.ini
        regexp: '^dhcp_domain ='
        line: 'dhcp_domain = {{ nova_domain }}'
    - name: Change dns_domain in neutron neutron.conf
      lineinfile:
        dest: /etc/neutron/neutron.conf
        regexp: '^dns_domain ='
        line: 'dns_domain = {{ nova_domain }}.'
    - name: Change extension_drivers in neutron ml2 plugins
      lineinfile:
        dest: /etc/neutron/plugins/ml2/ml2_conf.ini
        regexp: '^extension_drivers ='
        line: 'extension_drivers = qos,port_security,dns'

- hosts: controller
  name: Change DHCP/DNS Domain in nova and neutron
  become: yes
  vars_files:
    - vars.yml
  tasks:
    - name: Change dhcp_domain in nova.conf
      lineinfile:
        dest: /etc/nova/nova.conf
        regexp: '^dhcp_domain='
        line: 'dhcp_domain={{ nova_domain }}'
    - name: restart openstack-nova-api
      service:
        name: openstack-nova-api
        state: restarted
    - name: Change dhcp_domain in neutron dhcp_agent.ini
      lineinfile:
        dest: /etc/neutron/dhcp_agent.ini
        regexp: '^dhcp_domain ='
        line: 'dhcp_domain = {{ nova_domain }}'
    - name: Change dns_domain in neutron.conf
      lineinfile:
        dest: /etc/neutron/neutron.conf
        regexp: '^dns_domain ='
        line: 'dns_domain = {{ nova_domain }}.'
    - name: Change extension_drivers in neutron ml2 plugins
      lineinfile:
        dest: /etc/neutron/plugins/ml2/ml2_conf.ini
        regexp: '^extension_drivers ='
        line: 'extension_drivers = qos,port_security,dns'
    - name: restart neutron-server
      service:
        name: neutron-server
        state: restarted
    - name: restart neutron-dhcp-agent
      service:
        name: neutron-dhcp-agent
        state: restarted
